### ISSUE TITLE
Create Topic wise folders for all questions

### ISSUE THREAD

**Issue by ashutosh97** [ashutosh97/Competitive-Programming-questions#189]

**Comment by chauhanparth210** [comment]
Hi @ashutosh97, I am Parth Chauhan and I want to work on this issue. if you don't mind would you please assign this issue to me. Thank you @ashutosh97

**Comment by ashutosh97** [comment]
Go ahead @chauhanparth210

**Comment by chauhanparth210** [comment]
@ashutosh97  Thank you so much for assigning this re-arrangement. But I don't know all the classification I tried my best to resolve issue. For now not known algorithm  I make unknown folder to put the others' code.  So is this valid ??
